version: '3.3'
services:

  jenkins:
   image: jenkins-ansible-docker
   build:
    context: jenkins_ansible_docker
   privileged: true
   user: root
   ports:
    - "9999:8080"
    - "50000:50000"
   volumes:
    - "$PWD/jenkins_data:/var/jenkins_home"
    - "/var/run/docker.sock:/var/run/docker.sock"
   container_name: jenkins-AD
   networks:
    - net

  remote_host:
     container_name: remote_host
     image: remote_host
     build:
      context: centos
     volumes:
      - "$PWD/mysql_backup_and_upload_s3_bucket.sh:/tmp/script.sh"
     networks:
      - net

  db_host:
     container_name: db_host
     image: mysql:5.7
     networks:
       - net
     volumes:
       - "$PWD/db_data:/var/lib/mysql"
     environment:
       - "MYSQL_ROOT_PASSWORD=1234"

  web:
     container_name: web
     image: ansible-web
     build:
       context: jenkins_ansible/web
     ports:
      - "90:80"
     networks:
      - net

networks:
  net:
